### ISSUE TITLE
Step 2: Default front page after login

### ISSUE THREAD

**Issue by lucaswmy** [ivan0313/Intelligent-Know-Your-Customer#13]
After the user finishes registration or login, he will be redirected to his account page.

"Account" page contains the following (in vertical order):
- [ ] Name and login time
- [x] Customised welcome message #28 
- [ ] Total account balance
- [x] List of accounts #28 
- [x] Menu bar ("make transaction", "notification", "Add new account", and "Me") in the bottom #23
